name: Build Docker Image to Dockerhub

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build and Push to Dockerhub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v patch #major #patch

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       repository: ${{ github.repository}}
       #tag_with_ref: true
       #tag_with_sha: true
       tags: ${{ steps.increment-git-tag.outputs.git-tag }}